### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by techpeace** [nicolaserny/react-library-vite-example#1]
Howdy! Thanks so much for the [excellent tutorial post](https://dev.to/nicolaserny/create-a-react-component-library-with-vite-and-typescript-1ih9).

I was just wondering if you would consider [adding a license to the repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) so I know whether or not I can use this code in my projects.

**Comment by nicolaserny** [comment]
@techpeace, I've just added a license file. Feel free to use this code. :)

**Comment by techpeace** [comment]
Awesome, thank you!
